### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by tabbott**
Some general code review:

I improved performance on the cigar string -> parsed cigar array stuff by ~3.5x. I don't think it was an actual bottleneck but the code was bugging me.

I also refactored the left/right offset calculation code. In general, try to write less raw loops. Use algorithms (#include algorithm) when you can. In c++11/14, you get lambdas which makes doing so even more attractive (you don't have to write a bunch of little helper functions). In c++14, you can write:

return std::accumulate(beg, end, 0, [] (auto x, auto y) { if (want(y)) x += y; return x; });

I'm off to look at the other library now.

### CODE REVIEW

**Comment by tabbott** [comment]
Note that I added some new throws when invalid cigar data is seen. We'll want to catch those somewhere.

**Comment by tabbott** [comment]
I also may have increased the version requirement for boost. Not sure if 1.40 has the spirit parsing code I used. There's an internal package at TGI you can use, apt-cache search boost | egrep -i 'tgi|1.51' should reveal its name. It installs boost to /opt/boost-tgi/1.51 or /opt/tgi-boost/1.51, something like that.

**Comment by tabbott** [comment]
Also, don't merge this yet (assuming you even want to). I've got some more stuff coming.

**Comment by ernfrid** [comment]
Looked over most of this. I still need to look over the qi additions and try to understand them a bit better (although we have used them before).

Other than my earlier comment on dropping const, I had a few questions:

1) Any reason to prefer the `for` loop to a `while` loop in the cigar parsing code? 
2) Why did you change `Read` to a struct? I think your way reads much better with the is_on_same_tile functions instead of methods, but I'm curious if there are other advantages.

**Comment by tabbott** [comment]
It can be const if you like, the point was to make it not a reference. Passing small-ish types (i.e., smaller than a pointer) that you don't intend to modify by reference can be a bad idea. Some documentation can be found here:

http://www.boost.org/doc/libs/1_57_0/libs/utility/call_traits.htm

The basic idea: char const& (or minus the const even) forces a pointer sized addr to be passed. Removing the reference requirement lets the compiler do what it thinks is best. In your specific case (gcc 4.4 on ubuntu lucid), this probably isn't a huge deal, but in general:

pass by reference when the object is bigger than a pointer.
apply const when passing by reference and you don't intend to modify the var being accepted.

**Comment by tabbott** [comment]
for me, preferring 'for' over 'while' is often just a preference.

when faced with a situation like:

type x = x_initial_value;

where i need to do stuff until x satisfies some condition, i prefer:

```
for (; !condition(x); update(x)) {
    // do stuff with x
}
```

vs

````
while (!condition(x)) {
    // do stuff with x
    update(x);
}
```

**Comment by tabbott** [comment]
put differently, any for vs while changes were cosmetic :)

**Comment by ernfrid** [comment]
Ok. Good to know on both counts. I seem to have fallen into the trap of thinking that preventing the copy by passing by reference is always good. It took me awhile, but I think I get it.

**Comment by tabbott** [comment]
internalize the fact that something is always copied :)

**Comment by tabbott** [comment]
I'm going to have to ask you questions about the mainloop. I don't think it can scale (iterating over the whole hashtable for each 'valid' read, that can't be what you meant...)

**Comment by ernfrid** [comment]
Yes! That was the gap in my thinking on the pass by reference.

**Comment by tabbott** [comment]
How do you want to define duplicates? The current code misses out on all the benefits of hashing. If you need fuzzy matching, then we can look at some spatially aware data structures, but I think (perhaps incorrectly) that we're interested in matching up EXACT signatures.

**Comment by ernfrid** [comment]
Ya, the main program is by far the dirtiest in terms of slop. I was trying to conserve memory initially. Iterating over the entire table was not the original plan. It should stay fairly small as it gets cleared, but definitely not optimal. Let me think about a better way to do the same thing. 

I'm not sure what you meant about hashing unless you meant that by searching for duplicates to process by iterating over the whole thing, I'm killing all the speed benefits.

**Comment by ernfrid** [comment]
Also, I see what I was trying to do vs. what I am doing. I will fix it.

**Comment by tabbott** [comment]
If we're assuming (coord) sorted input, then there are some tricks we can play to produce bundles of potential dups. Being able to do something like fetch_a_bundle() and ship it off to a thread for further processing would help scalability greatly :)

**Comment by ernfrid** [comment]
That's what I'm aiming for. The dump loop is trying to identify which signatures have accumulated all of the duplicates they are going to. The problem is, with the way the clipping is unrolled, you can't quite guarantee that a dup won't appear a little farther down the line in the file than you might otherwise expect.

**Comment by tabbott** [comment]
Not even when considering end coords? I'm comparing this to what I did in joinx for merge/annotate/compare. Seems like it should be possible to detect "gaps" that indicate "no more overlaps are possible".

**Comment by tabbott** [comment]
Let me see if I'm smelling what you're selling.

Dups must start at the same position (clipping considered).
You are currently allowing up to a 300bp window for doing such (I think we can improve this to be actually correct in all cases with the cost of admitting some worst case scenarios that do not happen in practice).

Am I understanding the problem correctly?

**Comment by ernfrid** [comment]
I believe so.

**Comment by tabbott** [comment]
so it would be safe to spin+buffer reads until we see something that can't possibly overlap eh?

you see where i'm going.

**Comment by tabbott** [comment]
I implemented bundling. It changes the answers a bit (it reports more of everything). Let me know what you think.

**Comment by tabbott** [comment]
Here is the bundling logic:

https://github.com/genome/diagnose_dups/blob/code-review/src/lib/diagnose_dups/SignatureBundle.hpp#L23-L49

**Comment by tabbott** [comment]
and here is the logic to process a bundle. It should be mostly unchanged. The main difference is we build a hash on demand for the specific bundle rather than keeping a global hash for all time.

https://github.com/genome/diagnose_dups/blob/code-review/src/exe/diagnose-dups/diagnose_dups.cpp#L65-L90

Most of the other changes (e.g., making SamReader and BamRecord) were just for RAII so free() calls won't get missed when exceptions are thrown (still need to catch those).

**Comment by ernfrid** [comment]
This is getting kind of long so I'd like to merge. I've looked over the changes and I think I understand what you have done and why it's better. If you are ok with what I've done then I will merge and make further changes on a new topic branch.

**Comment by tabbott** [comment]
sounds good to me. keep me in the loop w.r.t. bugs though, I'm sure I've
introduced a few.

**Pull request merged**
